// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageCategory.proto

package com.tank.message;

public final class MessageCategoryProto {
  private MessageCategoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageCategoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tank.message.MessageCategory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
     */
    int getRequestTypeValue();
    /**
     * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
     */
    com.tank.message.MessageCategoryProto.MessageCategory.RequestType getRequestType();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.tank.message.MessageCategory}
   */
  public  static final class MessageCategory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tank.message.MessageCategory)
      MessageCategoryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageCategory.newBuilder() to construct.
    private MessageCategory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageCategory() {
      requestType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageCategory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              requestType_ = rawValue;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tank.message.MessageCategoryProto.internal_static_com_tank_message_MessageCategory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tank.message.MessageCategoryProto.internal_static_com_tank_message_MessageCategory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tank.message.MessageCategoryProto.MessageCategory.class, com.tank.message.MessageCategoryProto.MessageCategory.Builder.class);
    }

    /**
     * Protobuf enum {@code com.tank.message.MessageCategory.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN_REQUEST = 0;</code>
       */
      LOGIN_REQUEST(0),
      /**
       * <code>SEARCH_REQUEST = 1;</code>
       */
      SEARCH_REQUEST(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LOGIN_REQUEST = 0;</code>
       */
      public static final int LOGIN_REQUEST_VALUE = 0;
      /**
       * <code>SEARCH_REQUEST = 1;</code>
       */
      public static final int SEARCH_REQUEST_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return LOGIN_REQUEST;
          case 1: return SEARCH_REQUEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tank.message.MessageCategoryProto.MessageCategory.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.tank.message.MessageCategory.RequestType)
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private int requestType_;
    /**
     * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
     */
    public com.tank.message.MessageCategoryProto.MessageCategory.RequestType getRequestType() {
      com.tank.message.MessageCategoryProto.MessageCategory.RequestType result = com.tank.message.MessageCategoryProto.MessageCategory.RequestType.valueOf(requestType_);
      return result == null ? com.tank.message.MessageCategoryProto.MessageCategory.RequestType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestType_ != com.tank.message.MessageCategoryProto.MessageCategory.RequestType.LOGIN_REQUEST.getNumber()) {
        output.writeEnum(1, requestType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestType_ != com.tank.message.MessageCategoryProto.MessageCategory.RequestType.LOGIN_REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tank.message.MessageCategoryProto.MessageCategory)) {
        return super.equals(obj);
      }
      com.tank.message.MessageCategoryProto.MessageCategory other = (com.tank.message.MessageCategoryProto.MessageCategory) obj;

      boolean result = true;
      result = result && requestType_ == other.requestType_;
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tank.message.MessageCategoryProto.MessageCategory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tank.message.MessageCategoryProto.MessageCategory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tank.message.MessageCategory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tank.message.MessageCategory)
        com.tank.message.MessageCategoryProto.MessageCategoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tank.message.MessageCategoryProto.internal_static_com_tank_message_MessageCategory_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tank.message.MessageCategoryProto.internal_static_com_tank_message_MessageCategory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tank.message.MessageCategoryProto.MessageCategory.class, com.tank.message.MessageCategoryProto.MessageCategory.Builder.class);
      }

      // Construct using com.tank.message.MessageCategoryProto.MessageCategory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestType_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tank.message.MessageCategoryProto.internal_static_com_tank_message_MessageCategory_descriptor;
      }

      public com.tank.message.MessageCategoryProto.MessageCategory getDefaultInstanceForType() {
        return com.tank.message.MessageCategoryProto.MessageCategory.getDefaultInstance();
      }

      public com.tank.message.MessageCategoryProto.MessageCategory build() {
        com.tank.message.MessageCategoryProto.MessageCategory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tank.message.MessageCategoryProto.MessageCategory buildPartial() {
        com.tank.message.MessageCategoryProto.MessageCategory result = new com.tank.message.MessageCategoryProto.MessageCategory(this);
        result.requestType_ = requestType_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tank.message.MessageCategoryProto.MessageCategory) {
          return mergeFrom((com.tank.message.MessageCategoryProto.MessageCategory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tank.message.MessageCategoryProto.MessageCategory other) {
        if (other == com.tank.message.MessageCategoryProto.MessageCategory.getDefaultInstance()) return this;
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tank.message.MessageCategoryProto.MessageCategory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tank.message.MessageCategoryProto.MessageCategory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
       */
      public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
       */
      public com.tank.message.MessageCategoryProto.MessageCategory.RequestType getRequestType() {
        com.tank.message.MessageCategoryProto.MessageCategory.RequestType result = com.tank.message.MessageCategoryProto.MessageCategory.RequestType.valueOf(requestType_);
        return result == null ? com.tank.message.MessageCategoryProto.MessageCategory.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
       */
      public Builder setRequestType(com.tank.message.MessageCategoryProto.MessageCategory.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.tank.message.MessageCategory.RequestType requestType = 1;</code>
       */
      public Builder clearRequestType() {
        
        requestType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.tank.message.MessageCategory)
    }

    // @@protoc_insertion_point(class_scope:com.tank.message.MessageCategory)
    private static final com.tank.message.MessageCategoryProto.MessageCategory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tank.message.MessageCategoryProto.MessageCategory();
    }

    public static com.tank.message.MessageCategoryProto.MessageCategory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageCategory>
        PARSER = new com.google.protobuf.AbstractParser<MessageCategory>() {
      public MessageCategory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageCategory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageCategory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageCategory> getParserForType() {
      return PARSER;
    }

    public com.tank.message.MessageCategoryProto.MessageCategory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tank_message_MessageCategory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tank_message_MessageCategory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MessageCategory.proto\022\020com.tank.messag" +
      "e\"\231\001\n\017MessageCategory\022B\n\013requestType\030\001 \001" +
      "(\0162-.com.tank.message.MessageCategory.Re" +
      "questType\022\014\n\004data\030\002 \001(\014\"4\n\013RequestType\022\021" +
      "\n\rLOGIN_REQUEST\020\000\022\022\n\016SEARCH_REQUEST\020\001B\026B" +
      "\024MessageCategoryProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tank_message_MessageCategory_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tank_message_MessageCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tank_message_MessageCategory_descriptor,
        new java.lang.String[] { "RequestType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
